In [23]:
class HNP:
    def __init__(self, p, k, l):
        self.p = p
        self.k = k
        self.l = l
        self.x = [0] * l
        lam = 2**(k + 1)
        self.L = lam * p * matrix.identity(l+1)
        self.L[l, l] = 1
        for i in range(l):
            self.x[i] = int(ZZ.random_element(l))
            self.L[l,i] = lam * self.x[i]
        print(self.L)
        print(self.x)
        
    def msb(self, s):
        v = int(ZZ(s.bits()[-self.k::],2))
        return mod(v,self.p)

    def quo(self, s):
        return s//self.p
    
    def norm(self, matrix):
        m = -1
        for x in matrix:
            aux = min(abs(int(x)), self.p - abs(int(x)))
            if aux > m:
                m = aux
        return m

In [24]:
hnp = HNP(10,10,9)



s = ZZ.random_element(hnp.l)
while s == 0:
    s = ZZ.random_element(hnp.l)
print(s)

t = [0] * (hnp.l + 1)
w = [0] * (hnp.l + 1)
for i in range(hnp.l):
    val = hnp.x[i] * s
    t[i] = (2**(hnp.k + 1)) * hnp.msb(val)
    w[i] = -hnp.quo(int(val))
w[hnp.l] = s
print(t)
print(w)

[20480     0     0     0     0     0     0     0     0     0]
[    0 20480     0     0     0     0     0     0     0     0]
[    0     0 20480     0     0     0     0     0     0     0]
[    0     0     0 20480     0     0     0     0     0     0]
[    0     0     0     0 20480     0     0     0     0     0]
[    0     0     0     0     0 20480     0     0     0     0]
[    0     0     0     0     0     0 20480     0     0     0]
[    0     0     0     0     0     0     0 20480     0     0]
[    0     0     0     0     0     0     0     0 20480     0]
[16384  4096  4096     0 16384 14336  4096  4096 10240     1]
[8, 2, 2, 0, 8, 7, 2, 2, 5]
<type 'sage.rings.integer.Integer'>
<type 'sage.rings.integer.Integer'>
<type 'sage.rings.integer.Integer'>
6
[4, 6, 6, 0, 4, 6, 6, 6, 0, 0]
[-4, -1, -1, 0, -4, -4, -1, -1, -3, 6]


In [28]:
val = (vector(w)*hnp.L-vector(t))
print(val)

norm = int(str(hnp.norm(val)))
print("norm = " + str(norm))

print("p = " + str(hnp.p))
print(norm <= hnp.p)

alpha = vector(w) * hnp.L
print(alpha)

new_s = alpha[hnp.l]
print(new_s)

print(s == new_s)

(0, 0, 0, 0, 0, 0, 0, 0, 0, 6)
norm = 4
p = 10
True
(16384, 4096, 4096, 0, 16384, 4096, 4096, 4096, 0, 6)
6
True
